/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.mtp.extinterface.nbi.swagger.model.InlineResponse2001;
import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for RadioResourcesApi
 */
@Ignore
public class RadioResourcesApiTest {

    private final RadioResourcesApi api = new RadioResourcesApi();

    
    /**
     * Retrieve Radio Coverage Area info for Radio PoP capable
     *
     * Retrieve Radio Coverage Area info for Radio PoP capable
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void collectRadioCoverageareaInformationTest() throws ApiException {
        InlineResponse2001 response = api.collectRadioCoverageareaInformation();

        // TODO: test validations
    }
    
}
