# coding: utf-8

# flake8: noqa
"""
    5GT-MTP PA API

    REST-API for the MTP PA. Find more at http://5g-transformer.eu  # noqa: E501

    OpenAPI spec version: 0.0.0
    Contact: cnd@lists.cttc.es
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from pa.swagger_client.models.comp_route_input import CompRouteInput
from pa.swagger_client.models.comp_route_input_abs_wan_topo import CompRouteInputAbsWanTopo
from pa.swagger_client.models.comp_route_input_compute_reqs import CompRouteInputComputeReqs
from pa.swagger_client.models.comp_route_input_cpu_resource_attributes import CompRouteInputCpuResourceAttributes
from pa.swagger_client.models.comp_route_input_edges import CompRouteInputEdges
from pa.swagger_client.models.comp_route_input_inter_wan_links import CompRouteInputInterWanLinks
from pa.swagger_client.models.comp_route_input_memory_resource_attributes import CompRouteInputMemoryResourceAttributes
from pa.swagger_client.models.comp_route_input_netw_link_qo_s import CompRouteInputNetwLinkQoS
from pa.swagger_client.models.comp_route_input_nfvi_pop_reqs import CompRouteInputNfviPopReqs
from pa.swagger_client.models.comp_route_input_nfvi_pops import CompRouteInputNfviPops
from pa.swagger_client.models.comp_route_input_nodes import CompRouteInputNodes
from pa.swagger_client.models.comp_route_input_qos_cons import CompRouteInputQosCons
from pa.swagger_client.models.comp_route_input_resource_zone_attributes import CompRouteInputResourceZoneAttributes
from pa.swagger_client.models.comp_route_input_storage_resource_attributes import CompRouteInputStorageResourceAttributes
from pa.swagger_client.models.comp_route_output import CompRouteOutput
from pa.swagger_client.models.comp_route_output_item import CompRouteOutputItem
from pa.swagger_client.models.comp_route_output_item_inter_wan_links import CompRouteOutputItemInterWanLinks
from pa.swagger_client.models.comp_route_output_item_nfvi_pop_resp import CompRouteOutputItemNfviPopResp
from pa.swagger_client.models.comp_route_output_item_wan_path_elements import CompRouteOutputItemWanPathElements
from pa.swagger_client.models.comp_route_output_item_wan_paths import CompRouteOutputItemWanPaths
from pa.swagger_client.models.comp_route_output_item_zone_atts import CompRouteOutputItemZoneAtts
from pa.swagger_client.models.inline_response200 import InlineResponse200
