# coding: utf-8

"""
    5GT-MTP PA API

    REST-API for the MTP PA. Find more at http://5g-transformer.eu  # noqa: E501

    OpenAPI spec version: 0.0.0
    Contact: cnd@lists.cttc.es
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pa.swagger_client.models.comp_route_output import CompRouteOutput  # noqa: F401,E501


class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comp_route_output': 'CompRouteOutput'
    }

    attribute_map = {
        'comp_route_output': 'compRouteOutput'
    }

    def __init__(self, comp_route_output=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501

        self._comp_route_output = None
        self.discriminator = None

        if comp_route_output is not None:
            self.comp_route_output = comp_route_output

    @property
    def comp_route_output(self):
        """Gets the comp_route_output of this InlineResponse200.  # noqa: E501


        :return: The comp_route_output of this InlineResponse200.  # noqa: E501
        :rtype: CompRouteOutput
        """
        return self._comp_route_output

    @comp_route_output.setter
    def comp_route_output(self, comp_route_output):
        """Sets the comp_route_output of this InlineResponse200.


        :param comp_route_output: The comp_route_output of this InlineResponse200.  # noqa: E501
        :type: CompRouteOutput
        """

        self._comp_route_output = comp_route_output

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
