/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import com.mtp.extinterface.nbi.swagger.model.AllocateComputeRequest;
import com.mtp.extinterface.nbi.swagger.model.DeleteInterNfviPopConnectivityRequest;
import com.mtp.extinterface.nbi.swagger.model.InlineResponse2001;
import com.mtp.extinterface.nbi.swagger.model.InlineResponse201;
import com.mtp.extinterface.nbi.swagger.model.InterNfviPopConnectivityRequest;
import com.mtp.extinterface.nbi.swagger.model.VirtualCompute;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AbstractResourcesApi
 */
@Ignore
public class AbstractResourcesApiTest {

    private final AbstractResourcesApi api = new AbstractResourcesApi();

    
    /**
     * Allocate abstract compute resources
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void allocateAbstractComputeTest() throws ApiException {
        AllocateComputeRequest body = null;
        VirtualCompute response = api.allocateAbstractCompute(body);

        // TODO: test validations
    }
    
    /**
     * Retrieve aggregated Cloud NFVI-PoP and Inter-NFVI-PoP Connectivity
     *
     * Retrieve aggregated Cloud NFVI-PoP and Inter-NFVI-PoP Connectivity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void collectMtpCloudNetworkResourceInformationTest() throws ApiException {
        InlineResponse2001 response = api.collectMtpCloudNetworkResourceInformation();

        // TODO: test validations
    }
    
    /**
     * Create inter-NFVI-PoP connectivity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInterNfviPoPConnectivityTest() throws ApiException {
        InterNfviPopConnectivityRequest body = null;
        InlineResponse201 response = api.createInterNfviPoPConnectivity(body);

        // TODO: test validations
    }
    
    /**
     * Delete inter-NFVI-PoP connectivity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteInterNfviPoPConnectivityTest() throws ApiException {
        DeleteInterNfviPopConnectivityRequest body = null;
        api.deleteInterNfviPoPConnectivity(body);

        // TODO: test validations
    }
    
    /**
     * Terminate abstract compute resources
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void terminateResourcesTest() throws ApiException {
        List<String> computeId = null;
        List<String> response = api.terminateResources(computeId);

        // TODO: test validations
    }
    
}
