/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import com.mtp.extinterface.nbi.swagger.model.SoftwareImageAddQuery;
import com.mtp.extinterface.nbi.swagger.model.SoftwareImageInformation;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SoftwareImagesApi
 */
@Ignore
public class SoftwareImagesApiTest {

    private final SoftwareImagesApi api = new SoftwareImagesApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSoftwareImageTest() throws ApiException {
        SoftwareImageAddQuery body = null;
        SoftwareImageInformation response = api.addSoftwareImage(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSoftwareImageTest() throws ApiException {
        String id = null;
        String response = api.deleteSoftwareImage(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void querySoftwareImageTest() throws ApiException {
        String id = null;
        SoftwareImageInformation response = api.querySoftwareImage(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void querySoftwareImagesTest() throws ApiException {
        List<SoftwareImageInformation> response = api.querySoftwareImages();

        // TODO: test validations
    }
    
}
