/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import com.mtp.extinterface.nbi.swagger.model.CreateComputeResourceReservationRequest;
import com.mtp.extinterface.nbi.swagger.model.CreateNetworkResourceReservationRequest;
import com.mtp.extinterface.nbi.swagger.model.ReservedVirtualCompute;
import com.mtp.extinterface.nbi.swagger.model.ReservedVirtualNetwork;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VirtualisedResourceReservationApi
 */
@Ignore
public class VirtualisedResourceReservationApiTest {

    private final VirtualisedResourceReservationApi api = new VirtualisedResourceReservationApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createComputeReservationTest() throws ApiException {
        CreateComputeResourceReservationRequest body = null;
        ReservedVirtualCompute response = api.createComputeReservation(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNetworkReservationTest() throws ApiException {
        CreateNetworkResourceReservationRequest body = null;
        ReservedVirtualNetwork response = api.createNetworkReservation(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryComputeReservationTest() throws ApiException {
        List<ReservedVirtualCompute> response = api.queryComputeReservation();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryNetworkReservationTest() throws ApiException {
        List<ReservedVirtualNetwork> response = api.queryNetworkReservation();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void terminateComputeReservationTest() throws ApiException {
        List<String> reservationId = null;
        List<String> response = api.terminateComputeReservation(reservationId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void terminateNetworkReservationTest() throws ApiException {
        List<String> reservationId = null;
        List<String> response = api.terminateNetworkReservation(reservationId);

        // TODO: test validations
    }
    
}
