/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import com.mtp.extinterface.nbi.swagger.model.AllocateNetworkRequest;
import com.mtp.extinterface.nbi.swagger.model.AllocateNetworkResult;
import com.mtp.extinterface.nbi.swagger.model.CapacityInformation;
import com.mtp.extinterface.nbi.swagger.model.Filter;
import com.mtp.extinterface.nbi.swagger.model.NfviPop;
import com.mtp.extinterface.nbi.swagger.model.QueryNetworkCapacityRequest;
import com.mtp.extinterface.nbi.swagger.model.VirtualNetwork;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VirtualisedNetworkResourcesApi
 */
@Ignore
public class VirtualisedNetworkResourcesApiTest {

    private final VirtualisedNetworkResourcesApi api = new VirtualisedNetworkResourcesApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryNFVIPoPNetworkInformationTest() throws ApiException {
        Filter nfviPopNetworkInformationRequest = null;
        List<NfviPop> response = api.queryNFVIPoPNetworkInformation(nfviPopNetworkInformationRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryNetworkCapacityTest() throws ApiException {
        QueryNetworkCapacityRequest queryNetworkCapacityRequest = null;
        CapacityInformation response = api.queryNetworkCapacity(queryNetworkCapacityRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void vIMallocateNetworkTest() throws ApiException {
        AllocateNetworkRequest params = null;
        AllocateNetworkResult response = api.vIMallocateNetwork(params);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void vIMqueryNetworksTest() throws ApiException {
        Filter networkQueryFilter = null;
        List<VirtualNetwork> response = api.vIMqueryNetworks(networkQueryFilter);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void vIMterminateNetworksTest() throws ApiException {
        List<String> networkResourceId = null;
        List<String> response = api.vIMterminateNetworks(networkResourceId);

        // TODO: test validations
    }
    
}
