/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import com.mtp.extinterface.nbi.swagger.model.Filter;
import com.mtp.extinterface.nbi.swagger.model.VirtualNetworkResourceInformation;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VirtualisedNetworkResourcesInformationApi
 */
@Ignore
public class VirtualisedNetworkResourcesInformationApiTest {

    private final VirtualisedNetworkResourcesInformationApi api = new VirtualisedNetworkResourcesInformationApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryNetworkInformationTest() throws ApiException {
        Filter informationQueryFilter = null;
        List<VirtualNetworkResourceInformation> response = api.queryNetworkInformation(informationQueryFilter);

        // TODO: test validations
    }
    
}
