/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import com.mtp.extinterface.nbi.swagger.model.CreateComputeResourceQuotaRequest;
import com.mtp.extinterface.nbi.swagger.model.CreateNetworkResourceQuotaRequest;
import com.mtp.extinterface.nbi.swagger.model.ResourceGroupIds;
import com.mtp.extinterface.nbi.swagger.model.VirtualComputeQuota;
import com.mtp.extinterface.nbi.swagger.model.VirtualNetworkQuota;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VirtualisedResourceQuotaApi
 */
@Ignore
public class VirtualisedResourceQuotaApiTest {

    private final VirtualisedResourceQuotaApi api = new VirtualisedResourceQuotaApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createComputeQuotaTest() throws ApiException {
        CreateComputeResourceQuotaRequest body = null;
        VirtualComputeQuota response = api.createComputeQuota(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNetworkQuotaTest() throws ApiException {
        CreateNetworkResourceQuotaRequest body = null;
        VirtualNetworkQuota response = api.createNetworkQuota(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryComputeQuotaTest() throws ApiException {
        List<VirtualComputeQuota> response = api.queryComputeQuota();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryNetworkQuotaTest() throws ApiException {
        List<VirtualNetworkQuota> response = api.queryNetworkQuota();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void terminateComputeQuotaTest() throws ApiException {
        List<String> resourceGroupId = null;
        List<String> response = api.terminateComputeQuota(resourceGroupId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void terminateNetworkQuotaTest() throws ApiException {
        List<String> resourceGroupId = null;
        ResourceGroupIds response = api.terminateNetworkQuota(resourceGroupId);

        // TODO: test validations
    }
    
}
