/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mtp.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.mtp.extinterface.nbi.swagger.model.LogicalLinkInterNfviPops;
import com.mtp.extinterface.nbi.swagger.model.NfviPops;
import java.io.IOException;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-28T16:39:06.525Z")
public class InlineResponse2001 {
  @SerializedName("NfviPops")
  private NfviPops nfviPops = null;

  @SerializedName("logicalLinkInterNfviPops")
  private LogicalLinkInterNfviPops logicalLinkInterNfviPops = null;

  public InlineResponse2001 nfviPops(NfviPops nfviPops) {
    this.nfviPops = nfviPops;
    return this;
  }

   /**
   * Get nfviPops
   * @return nfviPops
  **/
  @ApiModelProperty(value = "")
  public NfviPops getNfviPops() {
    return nfviPops;
  }

  public void setNfviPops(NfviPops nfviPops) {
    this.nfviPops = nfviPops;
  }

  public InlineResponse2001 logicalLinkInterNfviPops(LogicalLinkInterNfviPops logicalLinkInterNfviPops) {
    this.logicalLinkInterNfviPops = logicalLinkInterNfviPops;
    return this;
  }

   /**
   * Get logicalLinkInterNfviPops
   * @return logicalLinkInterNfviPops
  **/
  @ApiModelProperty(value = "")
  public LogicalLinkInterNfviPops getLogicalLinkInterNfviPops() {
    return logicalLinkInterNfviPops;
  }

  public void setLogicalLinkInterNfviPops(LogicalLinkInterNfviPops logicalLinkInterNfviPops) {
    this.logicalLinkInterNfviPops = logicalLinkInterNfviPops;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.nfviPops, inlineResponse2001.nfviPops) &&
        Objects.equals(this.logicalLinkInterNfviPops, inlineResponse2001.logicalLinkInterNfviPops);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nfviPops, logicalLinkInterNfviPops);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    nfviPops: ").append(toIndentedString(nfviPops)).append("\n");
    sb.append("    logicalLinkInterNfviPops: ").append(toIndentedString(logicalLinkInterNfviPops)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

