/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mtp.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.mtp.extinterface.nbi.swagger.model.LogicalLinkPathList;
import com.mtp.extinterface.nbi.swagger.model.MetaData;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * InterNfviPopConnectivityRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-28T16:39:06.525Z")
public class InterNfviPopConnectivityRequest {
  @SerializedName("logicalLinkPathList")
  private LogicalLinkPathList logicalLinkPathList = null;

  @SerializedName("reqBandwidth")
  private BigDecimal reqBandwidth = null;

  @SerializedName("reqLatency")
  private BigDecimal reqLatency = null;

  @SerializedName("networkLayer")
  private String networkLayer = null;

  @SerializedName("interNfviPopNetworkType")
  private String interNfviPopNetworkType = null;

  @SerializedName("metaData")
  private MetaData metaData = null;

  public InterNfviPopConnectivityRequest logicalLinkPathList(LogicalLinkPathList logicalLinkPathList) {
    this.logicalLinkPathList = logicalLinkPathList;
    return this;
  }

   /**
   * Get logicalLinkPathList
   * @return logicalLinkPathList
  **/
  @ApiModelProperty(required = true, value = "")
  public LogicalLinkPathList getLogicalLinkPathList() {
    return logicalLinkPathList;
  }

  public void setLogicalLinkPathList(LogicalLinkPathList logicalLinkPathList) {
    this.logicalLinkPathList = logicalLinkPathList;
  }

  public InterNfviPopConnectivityRequest reqBandwidth(BigDecimal reqBandwidth) {
    this.reqBandwidth = reqBandwidth;
    return this;
  }

   /**
   * requested bandwidth (in Mbps).
   * @return reqBandwidth
  **/
  @ApiModelProperty(required = true, value = "requested bandwidth (in Mbps).")
  public BigDecimal getReqBandwidth() {
    return reqBandwidth;
  }

  public void setReqBandwidth(BigDecimal reqBandwidth) {
    this.reqBandwidth = reqBandwidth;
  }

  public InterNfviPopConnectivityRequest reqLatency(BigDecimal reqLatency) {
    this.reqLatency = reqLatency;
    return this;
  }

   /**
   * 5GT - requested maximum end-to-end latency (expressed in ms)
   * @return reqLatency
  **/
  @ApiModelProperty(required = true, value = "5GT - requested maximum end-to-end latency (expressed in ms)")
  public BigDecimal getReqLatency() {
    return reqLatency;
  }

  public void setReqLatency(BigDecimal reqLatency) {
    this.reqLatency = reqLatency;
  }

  public InterNfviPopConnectivityRequest networkLayer(String networkLayer) {
    this.networkLayer = networkLayer;
    return this;
  }

   /**
   * Get networkLayer
   * @return networkLayer
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNetworkLayer() {
    return networkLayer;
  }

  public void setNetworkLayer(String networkLayer) {
    this.networkLayer = networkLayer;
  }

  public InterNfviPopConnectivityRequest interNfviPopNetworkType(String interNfviPopNetworkType) {
    this.interNfviPopNetworkType = interNfviPopNetworkType;
    return this;
  }

   /**
   * Get interNfviPopNetworkType
   * @return interNfviPopNetworkType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getInterNfviPopNetworkType() {
    return interNfviPopNetworkType;
  }

  public void setInterNfviPopNetworkType(String interNfviPopNetworkType) {
    this.interNfviPopNetworkType = interNfviPopNetworkType;
  }

  public InterNfviPopConnectivityRequest metaData(MetaData metaData) {
    this.metaData = metaData;
    return this;
  }

   /**
   * Get metaData
   * @return metaData
  **/
  @ApiModelProperty(required = true, value = "")
  public MetaData getMetaData() {
    return metaData;
  }

  public void setMetaData(MetaData metaData) {
    this.metaData = metaData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterNfviPopConnectivityRequest interNfviPopConnectivityRequest = (InterNfviPopConnectivityRequest) o;
    return Objects.equals(this.logicalLinkPathList, interNfviPopConnectivityRequest.logicalLinkPathList) &&
        Objects.equals(this.reqBandwidth, interNfviPopConnectivityRequest.reqBandwidth) &&
        Objects.equals(this.reqLatency, interNfviPopConnectivityRequest.reqLatency) &&
        Objects.equals(this.networkLayer, interNfviPopConnectivityRequest.networkLayer) &&
        Objects.equals(this.interNfviPopNetworkType, interNfviPopConnectivityRequest.interNfviPopNetworkType) &&
        Objects.equals(this.metaData, interNfviPopConnectivityRequest.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logicalLinkPathList, reqBandwidth, reqLatency, networkLayer, interNfviPopNetworkType, metaData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterNfviPopConnectivityRequest {\n");
    
    sb.append("    logicalLinkPathList: ").append(toIndentedString(logicalLinkPathList)).append("\n");
    sb.append("    reqBandwidth: ").append(toIndentedString(reqBandwidth)).append("\n");
    sb.append("    reqLatency: ").append(toIndentedString(reqLatency)).append("\n");
    sb.append("    networkLayer: ").append(toIndentedString(networkLayer)).append("\n");
    sb.append("    interNfviPopNetworkType: ").append(toIndentedString(interNfviPopNetworkType)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

