/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mtp.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.mtp.extinterface.nbi.swagger.model.LogicalLinkAttributes;
import java.io.IOException;

/**
 * LogicalLinkPathListInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-28T16:39:06.525Z")
public class LogicalLinkPathListInner {
  @SerializedName("logicalLinkAttributes")
  private LogicalLinkAttributes logicalLinkAttributes = null;

  public LogicalLinkPathListInner logicalLinkAttributes(LogicalLinkAttributes logicalLinkAttributes) {
    this.logicalLinkAttributes = logicalLinkAttributes;
    return this;
  }

   /**
   * Get logicalLinkAttributes
   * @return logicalLinkAttributes
  **/
  @ApiModelProperty(required = true, value = "")
  public LogicalLinkAttributes getLogicalLinkAttributes() {
    return logicalLinkAttributes;
  }

  public void setLogicalLinkAttributes(LogicalLinkAttributes logicalLinkAttributes) {
    this.logicalLinkAttributes = logicalLinkAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogicalLinkPathListInner logicalLinkPathListInner = (LogicalLinkPathListInner) o;
    return Objects.equals(this.logicalLinkAttributes, logicalLinkPathListInner.logicalLinkAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logicalLinkAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogicalLinkPathListInner {\n");
    
    sb.append("    logicalLinkAttributes: ").append(toIndentedString(logicalLinkAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

