/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mtp.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.mtp.extinterface.nbi.swagger.model.NfviPopsInnerNfviPopAttributesNetworkConnectivityEndpoint;
import com.mtp.extinterface.nbi.swagger.model.NfviPopsInnerNfviPopAttributesResourceZoneAttributes;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * NfviPopsInnerNfviPopAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-28T16:39:06.525Z")
public class NfviPopsInnerNfviPopAttributes {
  @SerializedName("geographicalLocationInfo")
  private String geographicalLocationInfo = null;

  @SerializedName("vimId")
  private String vimId = null;

  @SerializedName("networkConnectivityEndpoint")
  private List<NfviPopsInnerNfviPopAttributesNetworkConnectivityEndpoint> networkConnectivityEndpoint = new ArrayList<NfviPopsInnerNfviPopAttributesNetworkConnectivityEndpoint>();

  @SerializedName("nfviPopId")
  private String nfviPopId = null;

  @SerializedName("resourceZoneAttributes")
  private List<NfviPopsInnerNfviPopAttributesResourceZoneAttributes> resourceZoneAttributes = new ArrayList<NfviPopsInnerNfviPopAttributesResourceZoneAttributes>();

  public NfviPopsInnerNfviPopAttributes geographicalLocationInfo(String geographicalLocationInfo) {
    this.geographicalLocationInfo = geographicalLocationInfo;
    return this;
  }

   /**
   * It provides information about the geographic location (e.g. geographic coordinates or address of the building, etc.) of the NFVI resources that the VIM manages.
   * @return geographicalLocationInfo
  **/
  @ApiModelProperty(required = true, value = "It provides information about the geographic location (e.g. geographic coordinates or address of the building, etc.) of the NFVI resources that the VIM manages.")
  public String getGeographicalLocationInfo() {
    return geographicalLocationInfo;
  }

  public void setGeographicalLocationInfo(String geographicalLocationInfo) {
    this.geographicalLocationInfo = geographicalLocationInfo;
  }

  public NfviPopsInnerNfviPopAttributes vimId(String vimId) {
    this.vimId = vimId;
    return this;
  }

   /**
   * Identification of the VIM.
   * @return vimId
  **/
  @ApiModelProperty(required = true, value = "Identification of the VIM.")
  public String getVimId() {
    return vimId;
  }

  public void setVimId(String vimId) {
    this.vimId = vimId;
  }

  public NfviPopsInnerNfviPopAttributes networkConnectivityEndpoint(List<NfviPopsInnerNfviPopAttributesNetworkConnectivityEndpoint> networkConnectivityEndpoint) {
    this.networkConnectivityEndpoint = networkConnectivityEndpoint;
    return this;
  }

  public NfviPopsInnerNfviPopAttributes addNetworkConnectivityEndpointItem(NfviPopsInnerNfviPopAttributesNetworkConnectivityEndpoint networkConnectivityEndpointItem) {
    this.networkConnectivityEndpoint.add(networkConnectivityEndpointItem);
    return this;
  }

   /**
   * Get networkConnectivityEndpoint
   * @return networkConnectivityEndpoint
  **/
  @ApiModelProperty(required = true, value = "")
  public List<NfviPopsInnerNfviPopAttributesNetworkConnectivityEndpoint> getNetworkConnectivityEndpoint() {
    return networkConnectivityEndpoint;
  }

  public void setNetworkConnectivityEndpoint(List<NfviPopsInnerNfviPopAttributesNetworkConnectivityEndpoint> networkConnectivityEndpoint) {
    this.networkConnectivityEndpoint = networkConnectivityEndpoint;
  }

  public NfviPopsInnerNfviPopAttributes nfviPopId(String nfviPopId) {
    this.nfviPopId = nfviPopId;
    return this;
  }

   /**
   * Identification of the NFVI-PoP.
   * @return nfviPopId
  **/
  @ApiModelProperty(required = true, value = "Identification of the NFVI-PoP.")
  public String getNfviPopId() {
    return nfviPopId;
  }

  public void setNfviPopId(String nfviPopId) {
    this.nfviPopId = nfviPopId;
  }

  public NfviPopsInnerNfviPopAttributes resourceZoneAttributes(List<NfviPopsInnerNfviPopAttributesResourceZoneAttributes> resourceZoneAttributes) {
    this.resourceZoneAttributes = resourceZoneAttributes;
    return this;
  }

  public NfviPopsInnerNfviPopAttributes addResourceZoneAttributesItem(NfviPopsInnerNfviPopAttributesResourceZoneAttributes resourceZoneAttributesItem) {
    this.resourceZoneAttributes.add(resourceZoneAttributesItem);
    return this;
  }

   /**
   * Get resourceZoneAttributes
   * @return resourceZoneAttributes
  **/
  @ApiModelProperty(required = true, value = "")
  public List<NfviPopsInnerNfviPopAttributesResourceZoneAttributes> getResourceZoneAttributes() {
    return resourceZoneAttributes;
  }

  public void setResourceZoneAttributes(List<NfviPopsInnerNfviPopAttributesResourceZoneAttributes> resourceZoneAttributes) {
    this.resourceZoneAttributes = resourceZoneAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NfviPopsInnerNfviPopAttributes nfviPopsInnerNfviPopAttributes = (NfviPopsInnerNfviPopAttributes) o;
    return Objects.equals(this.geographicalLocationInfo, nfviPopsInnerNfviPopAttributes.geographicalLocationInfo) &&
        Objects.equals(this.vimId, nfviPopsInnerNfviPopAttributes.vimId) &&
        Objects.equals(this.networkConnectivityEndpoint, nfviPopsInnerNfviPopAttributes.networkConnectivityEndpoint) &&
        Objects.equals(this.nfviPopId, nfviPopsInnerNfviPopAttributes.nfviPopId) &&
        Objects.equals(this.resourceZoneAttributes, nfviPopsInnerNfviPopAttributes.resourceZoneAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geographicalLocationInfo, vimId, networkConnectivityEndpoint, nfviPopId, resourceZoneAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NfviPopsInnerNfviPopAttributes {\n");
    
    sb.append("    geographicalLocationInfo: ").append(toIndentedString(geographicalLocationInfo)).append("\n");
    sb.append("    vimId: ").append(toIndentedString(vimId)).append("\n");
    sb.append("    networkConnectivityEndpoint: ").append(toIndentedString(networkConnectivityEndpoint)).append("\n");
    sb.append("    nfviPopId: ").append(toIndentedString(nfviPopId)).append("\n");
    sb.append("    resourceZoneAttributes: ").append(toIndentedString(resourceZoneAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

